#!/bin/bash
#This is a bash script to install the necessary file and configure them.
apt-get install hostapd
echo "interface=wlan0
driver=nl80211
ssid=Ubuntu_Hotspot
hw_mode=g
auth_algs=1
wpa=2
wpa_passphrase=123456789
wpa_pairwise=TKIP CCMP
wpa_key_mgmt=WPA-PSK
channel=1
rsn_pairwise=CCMP" > /etc/hostapd/hostapd.conf
apt-get purge dhcpd
apt-get install dnsmasq
echo "DNSMASQ_OPTS=" -conf-file=/etc/dnsmasq.conf"" >/etc/default/dnsmasq
echo "interface=wlan0
dhcp-range=10.0.0.2,10.0.0.127,255.255.255.0,24h " > /etc/dnsmasq.conf
chmod a+x hotspot
cp hotspot /usr/bin/hotspot
echo "Thank you for installing hotspot."
echo "To know usgae type sudo hotsopt in the terminal."
echo "Do you want to install minidlna-  A tiny dlna server??"
read -p "Press Y/n for your answer." ans


   			if [[ "$ans" == "Y" || "$ans" == "y" ]]
 				then
 					apt-get install minidlna
          				echo "Please edit '/etc/minidlna.conf' to fulfill your need."
						
				elif [[ "$ans" == "N" || "$ans" == "n" ]]
 					then
					echo "Thank you. Good bye. Enjoy."
 					
 				else 
 					
 					echo "I could not understand your answer" 		
			fi
exit 
